### ISSUE TITLE
Frontend & Backend connection error

### ISSUE THREAD

**Issue by makkahwi** [creativetimofficial/vue-now-ui-dashboard-laravel#1]
It looks like frontend & backend connection have an issue

When everything is setup n both apps are running, frontend is showing an empty page & cmd shows an error message of 
"export 'VueAuthenticate' was not found in 'vue-authenticate'"

When this line if fixed to be
import { VueAuthenticate } from "vue-authenticate"; => import VueAuthenticate from "vue-authenticate";
The application works and the login page show up, but can't login or register 
@ login it says "Invalid credentials!" although the default user is seeded into database
@ register it says "something went wrong"

**Comment by teamupdivision** [comment]
Hi @makkahwi,

Thanks for reporting this issue and for using Creative Tim products.

We've pushed a fix to this problem.
You can either download again the product from the downloads section in the Creative Tim website or check the latest commit we did in this Github repository: https://github.com/creativetimofficial/vue-now-ui-dashboard-laravel/

All the best
UPDIVISION Team

**Comment by makkahwi** [comment]
It was solved

**Comment by teamupdivision** [comment]
Hi there @makkahwi, 

Thank you for letting us know. We're glad this was solved. Please let us know in case there is anything else we can help with related to this. 

All the best,
Updivision Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
