### ISSUE TITLE
Issues with Installation on Laravel 9 and PHP 8.1.4

### ISSUE THREAD

**Issue by iamB0rgy** [creativetimofficial/vue-now-ui-dashboard-laravel#3]
PS C:\xampp\htdocs\now> composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.4 but your php version (8.1.4) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires lcobucci/jwt ^3.4.0 -> satisfiable by lcobucci/jwt[3.4.0, ..., 3.4.x-dev].
    - lcobucci/jwt[3.4.0, ..., 3.4.x-dev] require php ^5.6 || ^7.0 -> your php version (8.1.4) does not satisfy that requirement.
  Problem 3
    - laravel/passport[v10.1.0, ..., 10.x-dev] require lcobucci/jwt ^3.4|^4.0 -> satisfiable by lcobucci/jwt[3.4.0, ..., 3.4.x-dev].
    - lcobucci/jwt[3.4.0, ..., 3.4.x-dev] require php ^5.6 || ^7.0 -> your php version (8.1.4) does not satisfy that requirement.
    - Root composer.json requires laravel/passport ^10.1.0 -> satisfiable by laravel/passport[v10.1.0, ..., 10.x-dev].

PS C:\xampp\htdocs\now>

**Comment by teamupdivision** [comment]
Hello @iamB0rgy,

We updated from Laravel 8 to Laravel 9 five days ago. Can you please try installing it again? It should work now.

Thank you for informing us of this issue.

**Comment by teamupdivision** [comment]
Hi @iamB0rgy,

We will go ahead and close this ticket for now. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team
